Scalingo/developers-documentation

_database_api/backups.md
_database_api/databases.md
_database_api/index.md
_database_api/logs.md
_database_api/metrics.md

Rename BEARER_TOKEN -> DB_BEARER_TOKEN

---

_scalingo_api/domains.md

Add letsencrypt fields to domain

---

_scalingo_api/alerts.md

[alerts] duration_before_trigger is an int

---

_scalingo_api/notifications.md

Add missing type parameter to notification doc

---

_scalingo_api/notifications.md

Update notifier docs

---

_addon_provider_api/app.md
_scalingo_api/addon_providers.md
_scalingo_api/addons.md
_scalingo_api/alerts.md
_scalingo_api/apps.md
_scalingo_api/audit_logs.md
_scalingo_api/autoscalers.md
_scalingo_api/billing.md
_scalingo_api/collaborators.md
_scalingo_api/container-sizes.md
_scalingo_api/deployments.md
_scalingo_api/domains.md
_scalingo_api/environment.md
_scalingo_api/event_categories.md
_scalingo_api/event_types.md
_scalingo_api/events.md
_scalingo_api/index.md
_scalingo_api/invoices.md
_scalingo_api/metrics.md
_scalingo_api/notification_platforms.md
_scalingo_api/notifications.md
_scalingo_api/notifiers.md
_scalingo_api/operations.md
_scalingo_api/sources.md

Related to Scalingo/documentation#602

Add new region URL

---

_database_api/backups.md
_database_api/databases.md
_database_api/metrics.md
_scalingo_api/alerts.md
_scalingo_api/autoscalers.md
_scalingo_api/event_categories.md

Add doc about backup create

---

_database_api/databases.md

Related to Scalingo/appsdeck-database#1181

periodic_backups_scheduled_at is an array of int

---

.ackrc
_scalingo_api/index.md
_scalingo_api/keys.md
_scalingo_api/scm_integrations.md

Added doc about SCM integrations

---

_scalingo_api/notifiers.md

Various fix for the Notifiers API page

---

_scalingo_api/scm_repo_link.md

Add repo link update doc

---

_scalingo_api/scm_repo_link.md

Manual deploy returns a deployment

---

_scalingo_api/keys.md

[SSH Keys] Show and create returns a single key and not an array

---

_scalingo_api/scm_integrations.md

Add missing doc about SCM integrations endpoints

---

_scalingo_api/invoices.md
_scalingo_api/referral.md

Add referrals/stats endpoint documentation

---

_scalingo_api/regions.md

[Regions] Copy-paste error

---

_scalingo_api/log_drains.md

Related https://github.com/Scalingo/api/pull/1678
Related https://github.com/Scalingo/api/pull/1679
Related https://github.com/Scalingo/api/pull/1704
Related https://github.com/Scalingo/api/pull/1714

Add log drains: list, add and remove endpoints

---

_database_api/databases.md

modified titles for better autogenerated IDs fix #102

---

_scalingo_json_schema/index.md

Explain how to specify the review app addon version

---

_scalingo_api/deployments.md

[Deployments] Add queued status

---

_scalingo_api/collaborators.md

Invite endpoint returns a single collaborator

---

_scalingo_api/addons.md

Document get SSO endpoint

---

_scalingo_api/addons.md

Document the get addon endpoint

---

_scalingo_api/scm_repo_link.md

Related to https://github.com/Scalingo/api/pull/1782

Add documentation for GET /scm_repo_links

---

_scalingo_api/events.md

Add missing events

---

_scalingo_api/alerts.md
_scalingo_api/notification_platforms.md

[Notification Platform] Add doc about search and show

---

_database_api/metrics.md
_scalingo_api/apps.md
_scalingo_api/autoscalers.md
_scalingo_api/metrics.md

Add a link in the Metrics page to the "app metrics" endpoint

---

_scalingo_api/collaborators.md
_scalingo_api/domains.md
_scalingo_api/notifiers.md
_scalingo_api/user.md

Document endpoints for users self, update and destroy

---

_scalingo_api/user.md

Add the documentation about the /account/usage route

---

_database_api/database_type_versions.md

[Database Type Version] Document the show endpoint

---

_database_api/backups.md
_database_api/databases.md
_database_api/logs.md
_database_api/metrics.md
_database_api/users.md

Document the Users API

---

css/main.sass

fix: show result panel

---

_scalingo_api/apps.md

feature(apps): Add `limits` field to the payload and add a bit of doc for this field

---

_scalingo_api/apps.md

Related to [OPSB-254]
[OPSB-254]: https://scalingo.atlassian.net/browse/OPSB-254

docs(app): document the new ps route

---

_scalingo_api/domains.md

Dependent https://github.com/Scalingo/api/pull/1841

feat: add ssl_status to domain

---

_database_api/databases.md

feature(upgrade_database) Add the endpoint to upgrade a database

---

_scalingo_json_schema/index.md

docs(scalingo.json): explain when it is read by the platform

---

_scalingo_api/index.md

Fix https://github.com/Scalingo/one-stop-shop/issues/265

Replace Ember.js by Vue.js

---

_scalingo_api/cron_tasks.md

Related to [CRON-48]
[CRON-48]: https://scalingo.atlassian.net/browse/CRON-48

Add documentation for cron tasks endpoints

---

css/main.sass

- feat: upgrade DocSearch before end of life of version 2
- fix: bootstrap issue with Docsearch

upgrade docsearch

---

README.md
_scalingo_api/data_access_consents.md
_scalingo_json_schema/index.md

[UFSSP-39]
[UFSSP-39]: https://scalingo.atlassian.net/browse/UFSSP-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: documentation for data access consent get and post

---

_scalingo_api/data_access_consents.md

Typo data-access-consents

---

_scalingo_api/data_access_consents.md

[API-85]
[API-85]: https://scalingo.atlassian.net/browse/API-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: update DataAccessConsent app_id, user_id & end_at format

---

_scalingo_api/events.md

[UFSSP-22]
[UFSSP-22]: https://scalingo.atlassian.net/browse/UFSSP-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: data access consent creates an event

---

_scalingo_api/stacks.md

Refs. https://github.com/Scalingo/api/issues/1831
Fixes https://github.com/Scalingo/developers-documentation/issues/234

feat(stacks): Add deprecation date to stacks

---

_database_api/databases.md

feat(db-api) Document features endpoints

---

_scalingo_api/apps.md

This documentation part is relative to the changes made here https://github.com/Scalingo/api/pull/2096
Fix #263

feat(send-signal): kill documentation

---

_database_api/backups.md

Update response of backup api cause actually documentation is out-of-date

docs(api-backup): update response

---

_scalingo_api/scm_repo_link.md

feat: documentation for creating and updating integration links about automatic review apps from forks

---

_scalingo_api/region_migrations.md

docs(region_migrations): add endpoints

---

_scalingo_api/events.md

doc: events when creating and updating a review app

---

_scalingo_api/events.md

doc: add documentation on review apps interactions

---

_database_api/databases.md

feat(databases): add maintenance windows

---

_database_api/maintenance.md

feat(databases): add maintenance

---

_database_api/maintenance.md

Maintenance fix typo

---

_scalingo_json_schema/index.md

feat(scalingo_json_schema): add required field

---

_scalingo_api/scm_repo_link.md

docs(scm_repo_link): list PR endpoint

---

_scalingo_api/events.md

fixes #334
fixes #353
fixes #354

feat(events): documentation on database maintenance events [STORY-64 STORY-73 STORY-74]

---

_database_api/users.md

Fix https://github.com/Scalingo/developers-documentation/issues/363

feat: add docs about password encryption algorithm of users

---

_database_api/databases.md

fix(databases): add new feature pending statuses

---

_scalingo_api/apps.md

fix https://github.com/Scalingo/project-items/issues/337

feat(one-off): Document limits of one-off containers

---

_scalingo_api/apps.md

fix(one-off): remove async from body

---

_database_api/users.md
docker-compose.yml

docs(database): endpoint to update a user

---

_database_api/databases.md

I noticed this while working on the new DB dashboard project

docs(databases): missing fields

---

_scalingo_api/apps.md
_scalingo_api/one-off.md

fix(operation_url) : AppsController#run: it is difficult, sometimes impossible, to get the operation_url from the Location header with some (a lot of) http clients

fix(one_off) : fixing example

---

_scalingo_api/events.md

Update doc to reflect changes made by https://github.com/Scalingo/api/pull/2685

[STORY-1429] Add a new event for collaborator role change

---

_scalingo_api/collaborators.md

[STORY-1430] Add is_limited to the invitation

---

_scalingo_api/events.md

[STORY-2061] Add Event::NewProject event

---

_scalingo_api/index.md

Handle 409 error

---

_scalingo_api/apps.md

task - add project_id in apps#create
